# ==================== Redstone Music Box · load ====================
# Scoreboard naming (all abbreviated):
#   menu / lrc / play              —— player commands (trigger)
#   mb_*                           —— internal state
#   music_type / nbs_s / nbs_t     —— song playback contract, do not rename! Songs generated by this skill depend on these three

# --- Song playback contract ---
scoreboard objectives add music_type dummy
scoreboard objectives add nbs_s dummy
scoreboard objectives add nbs_t dummy
scoreboard players set #speed nbs_s 80

# --- Player commands ---
scoreboard objectives add menu trigger
scoreboard objectives add lrc trigger
scoreboard objectives add play trigger

# --- Internal state ---
scoreboard objectives add mb_song dummy
scoreboard objectives add mb_lyc dummy
scoreboard objectives add mb_pls dummy
scoreboard objectives add mb_rct dummy
scoreboard objectives add mb_hol dummy
scoreboard objectives add mb_hct dummy
scoreboard objectives add mb_don dummy
scoreboard objectives add mb_uct dummy
scoreboard objectives add mb_udo dummy
scoreboard objectives add mb_msg dummy
scoreboard objectives add mb_cfg dummy

# --- Default configuration values (all fake players live on mb_cfg) ---
scoreboard players set #pau mb_cfg 0
scoreboard players set #ban mb_cfg 1
scoreboard players set #dim_o mb_cfg 0
scoreboard players set #dim_n mb_cfg 0
scoreboard players set #dim_e mb_cfg 0
scoreboard players set #dim_any mb_cfg 0
scoreboard players set #max mb_cfg 0
scoreboard players set #cur mb_cfg 0
scoreboard players set #act mb_cfg 0
scoreboard players set @a mb_msg 0

# --- Allow players to use trigger (a trigger expires once used, so it must be re-enabled every tick) ---
scoreboard players enable @a menu
scoreboard players enable @a lrc
scoreboard players enable @a play

# --- Load message ---
title @a title "已成功加载音乐数据包"
title @a subtitle "输入 /trigger menu 获取红石音乐盒"
tellraw @a ["",{"text":"[音乐盒] ","color":"gold","bold":true},{"text":"已成功加载音乐数据包","color":"white"},{"text":"（通用框架，尚未添加歌曲）","color":"dark_gray"},{"text":"\n  /trigger menu","color":"yellow"},{"text":" 获取 / 收回唱片机","color":"gray"},{"text":"\n  /trigger lrc","color":"yellow"},{"text":" 开关歌词","color":"gray"},{"text":"\n  /trigger play set <编号>","color":"yellow"},{"text":" 点歌（也可点菜单里的歌名）","color":"gray"}]

# --- Song list (maintained by scripts/add_to_musicbox.py) ---
function rmb:song/max
