#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Register a song into the "Redstone Music Box" generic datapack (or remove it from the box).

Songs follow this skill's timeline contract (music_type / nbs_s / nbs_t + #speed 80),
so the box only handles "pick a song + dispatch"; the song itself is generated by generate.py.

Usage:
    # register from song.json (the next id is allocated automatically)
    python3 scripts/add_to_musicbox.py --box out/musicbox --song song.json --name "song name"
    # straight from MIDI in one step, lyrics included
    python3 scripts/add_to_musicbox.py --box out/musicbox --song song.mid --name "Lemon" --lrc lyrics.lrc
    # pick an id / remove / list
    python3 scripts/add_to_musicbox.py --box out/musicbox --song song.json --id 3
    python3 scripts/add_to_musicbox.py --box out/musicbox --remove 3
    python3 scripts/add_to_musicbox.py --box out/musicbox --list

After registering you must /reload for it to take effect (the files added are new function files).
Standard library only.
"""
import argparse, json, os, re, shutil, subprocess, sys

try:
    sys.stdout.reconfigure(errors="replace")
except Exception:
    pass

HERE = os.path.dirname(os.path.abspath(__file__))
GENERATE = os.path.join(HERE, "generate.py")
MIDI2SONG = os.path.join(HERE, "midi_to_song.py")
MANIFEST = "musicbox_songs.json"
SONG_DIR = "data/rmb/function/song"


# --------------------------------------------------------------------------- LRC
def parse_lrc(path):
    """[mm:ss.xx]text → [(seconds, text), ...] (multiple timestamps on one line expand into several entries)"""
    out = []
    for raw in open(path, encoding="utf-8-sig", errors="replace").read().splitlines():
        stamps = re.findall(r"\[(\d+):(\d+(?:[.:]\d+)?)\]", raw)
        text = re.sub(r"\[\d+:[\d.:]+\]", "", raw).strip()
        if not stamps:
            continue
        for mm, ss in stamps:
            sec = int(mm) * 60 + float(ss.replace(":", "."))
            if text:
                out.append((sec, text))
    out.sort(key=lambda x: x[0])
    return out


def lrc_function(song_id, lines, tick_rate=20):
    """lyrics function: uses nbs_s as the timeline (it advances every tick, so it also stops while paused/banned)"""
    L = ["# lyrics —— automatically generated by scripts/add_to_musicbox.py (timeline uses nbs_s)",
         "execute unless score music_progress music_type matches %d run return 0" % song_id]
    if not lines:
        L.append("# this song has no lyrics")
        return "\n".join(L)
    for i, (sec, text) in enumerate(lines):
        a = int(round(sec * tick_rate))
        # scoreboards are 32-bit integers: nbs_s must never be written above 2147483647
        b = int(round(lines[i + 1][0] * tick_rate)) if i + 1 < len(lines) else 2147483647 // 80
        if b <= a:
            b = a + 1
        L.append('execute if score music_progress nbs_s matches %d..%d run title @s actionbar %s'
                 % (a * 80, min(b * 80 - 1, 2147483647), json.dumps({"text": text}, ensure_ascii=False)))
    return "\n".join(L)


# --------------------------------------------------------------------------- writing
def w(path, text, crlf=False):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    # Append the trailing newline BEFORE converting to CRLF, otherwise the last line ends in a bare
    # LF while the rest of the file is CRLF (the repo's checkers want consistent CRLF in .mcfunction).
    if not text.endswith("\n"):
        text += "\n"
    if crlf:
        text = text.replace("\n", "\r\n")
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(text)


def load_manifest(box):
    p = os.path.join(box, MANIFEST)
    if os.path.isfile(p):
        return json.load(open(p, encoding="utf-8"))
    return []


def save_manifest(box, songs):
    songs = sorted(songs, key=lambda s: s["id"])
    with open(os.path.join(box, MANIFEST), "w", encoding="utf-8") as f:
        json.dump(songs, f, ensure_ascii=False, indent=1)
    return songs


def regenerate_registry(box, songs):
    """Regenerate the four files max / name / by_name / menu_list."""
    mx = max([s["id"] for s in songs], default=0)

    w(os.path.join(box, SONG_DIR, "max.mcfunction"),
      "# Song count —— generated automatically by scripts/add_to_musicbox.py\n"
      "scoreboard players set #max mb_cfg %d" % mx, crlf=True)

    L = ["# Current song name subtitle —— generated automatically by scripts/add_to_musicbox.py"]
    for s in songs:
        # in-game text is Chinese (see examples/musicbox/README.md); comments above stay English
        L.append('execute if score music_progress music_type matches %d run title @a actionbar %s'
                 % (s["id"], json.dumps({"text": "♪ 正在播放：" + s["name"]}, ensure_ascii=False)))
    L.append("scoreboard players set @a mb_msg 40")
    w(os.path.join(box, SONG_DIR, "name.mcfunction"), "\n".join(L), crlf=True)

    L = ["# Song name → id —— generated automatically by scripts/add_to_musicbox.py"]
    for s in songs:
        L.append('execute if data storage rmb:io arg{song:%s} run scoreboard players set #cur mb_cfg %d'
                 % (json.dumps(s["name"], ensure_ascii=False), s["id"]))
    w(os.path.join(box, SONG_DIR, "by_name.mcfunction"), "\n".join(L), crlf=True)

    L = ["# Song list —— generated automatically by scripts/add_to_musicbox.py, do not edit by hand"]
    if not songs:
        L += ['tellraw @s ["",{"text":"[音乐盒] ","color":"gold"},{"text":"还没有添加歌曲。","color":"yellow"}]',
              'tellraw @s ["",{"text":"  用 ","color":"gray"},{"text":"python3 scripts/add_to_musicbox.py --box <数据包> --song song.json","color":"white"},{"text":" 注册歌曲","color":"gray"}]',
              'tellraw @s ["",{"text":"  注册后这里会出现可点击的歌名。","color":"dark_gray"}]']
    for s in songs:
        L.append("tellraw @s " + json.dumps(["", {"text": "[%d] " % s["id"], "color": "gray"},
                                             {"text": s["name"], "color": "white",
                                              "clickEvent": {"action": "run_command",
                                                             "value": "/trigger play set %d" % s["id"]},
                                              "hoverEvent": {"action": "show_text",
                                                             "value": "点击播放 " + s["name"]}}],
                                            ensure_ascii=False))
    if songs:
        L.append('tellraw @s ["",{"text":"共 %d 首；也可 /function rmb:play {song:\\"歌名\\"} 按名字点歌","color":"dark_gray"}]' % len(songs))
    w(os.path.join(box, "data/rmb/function/box/menu_list.mcfunction"), "\n".join(L), crlf=True)


# --------------------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser(description="register songs into a Redstone Music Box datapack")
    ap.add_argument("--box", required=True, help="music box datapack directory (the one containing pack.mcmeta)")
    ap.add_argument("--song", default=None, help="song.json or .mid (a .mid is arranged automatically first)")
    ap.add_argument("--name", default=None, help="song name shown in the menu (defaults to meta.name from song.json)")
    ap.add_argument("--id", type=int, default=None, help="explicit song id (defaults to the next free one)")
    ap.add_argument("--lrc", default=None, help="lyrics file (LRC format, optional)")
    ap.add_argument("--mc-version", default="26.2", help="target version when arranging from a .mid")
    ap.add_argument("--song-id-conflict", action="store_true", help="allow overwriting an existing id")
    ap.add_argument("--remove", type=int, default=None, help="remove the song with this id")
    ap.add_argument("--list", action="store_true", help="only list the registered songs")
    a = ap.parse_args()

    box = os.path.abspath(a.box)
    if not os.path.isfile(os.path.join(box, "pack.mcmeta")):
        sys.exit("--box %s does not look like a datapack directory (no pack.mcmeta)" % box)
    songs = load_manifest(box)

    if a.list:
        print("%d songs registered:" % len(songs))
        for s in songs:
            print("  [%d] %s" % (s["id"], s["name"]))
        print("song count #max = %d" % max([s["id"] for s in songs], default=0))
        return 0

    if a.remove is not None:
        hit = [s for s in songs if s["id"] == a.remove]
        if not hit:
            sys.exit("no song with id %d" % a.remove)
        songs = [s for s in songs if s["id"] != a.remove]
        d = os.path.join(box, SONG_DIR, str(a.remove))
        if os.path.isdir(d):
            shutil.rmtree(d)
        regenerate_registry(box, save_manifest(box, songs))
        print("removed [%d] %s (remember to /reload; ids do not close the gap automatically, use --id to fill the hole)"
              % (a.remove, hit[0]["name"]))
        return 0

    if not a.song:
        sys.exit("--song (song.json or .mid) is required, or use --list / --remove")

    # ---- 1. prepare song.json ----
    src = os.path.abspath(a.song)
    tmp_song = None
    if src.lower().endswith((".mid", ".midi")):
        tmp_song = os.path.join(box, ".import.song.json")
        name = a.name or os.path.splitext(os.path.basename(src))[0]
        cmd = [sys.executable, MIDI2SONG, src, "-o", tmp_song, "--name", re.sub(r"[^0-9a-zA-Z_]+", "_", name).lower(),
               "--namespace", "rmb", "--mc-version", a.mc_version]
        r = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        try:
            sys.stdout.buffer.write(r.stdout)
            sys.stdout.buffer.flush()
        except Exception:
            pass
        if r.returncode != 0:
            sys.exit("midi_to_song.py failed")
        song_path = tmp_song
    else:
        song_path = src
    song = json.load(open(song_path, encoding="utf-8"))

    # ---- 2. decide the id ----
    name = a.name or song.get("meta", {}).get("name") or "unnamed"
    if a.id is not None:
        sid = a.id
    else:
        sid = max([s["id"] for s in songs], default=0) + 1
    if any(s["id"] == sid for s in songs) and not a.song_id_conflict:
        sys.exit("id %d is already taken by [%s]; use another --id, or add --song-id-conflict to overwrite"
                 % (sid, [s["name"] for s in songs if s["id"] == sid][0]))
    if sid < 1:
        sys.exit("id must be ≥ 1")

    # ---- 3. rewrite meta and generate the song functions ----
    song.setdefault("meta", {})
    song["meta"].update({
        "namespace": "rmb",
        "path": "song/%d" % sid,
        "song_id": sid,
        "style": "lemon",              # no _standalone_* helper files; the box handles init
        "next_song": "rmb:song/ended",  # automatically play the next song when this one ends
        "time_unit": song["meta"].get("time_unit", "nbs_s_units"),
        "speed": 80,
        "auto_stop": True,
    })
    out_dir = os.path.join(box, SONG_DIR, str(sid))
    if os.path.isdir(out_dir):
        shutil.rmtree(out_dir)
    w(os.path.join(box, ".build.song.json"), json.dumps(song, ensure_ascii=False))
    cmd = [sys.executable, GENERATE, os.path.join(box, ".build.song.json"), "-o", out_dir, "--speed", "80"]
    r = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    try:
        sys.stdout.buffer.write(r.stdout)
        sys.stdout.buffer.flush()
    except Exception:
        pass
    if r.returncode != 0:
        sys.exit("generate.py failed")

    # ---- 4. lyrics ----
    lines = parse_lrc(a.lrc) if a.lrc else []
    w(os.path.join(out_dir, "lrc.mcfunction"), lrc_function(sid, lines), crlf=True)

    # ---- 5. update the manifest and the registry ----
    songs = [s for s in songs if s["id"] != sid]
    songs.append({"id": sid, "name": name, "notes": sum(len(t["notes"]) for t in song.get("tracks", []))})
    regenerate_registry(box, save_manifest(box, songs))

    for junk in (".import.song.json", ".build.song.json"):
        p = os.path.join(box, junk)
        if os.path.isfile(p):
            os.remove(p)

    print("registered [%d] %s → %s" % (sid, name, os.path.relpath(out_dir, box).replace(os.sep, "/")))
    if lines:
        print("  lyrics: %d lines (toggle with /trigger lrc)" % len(lines))
    print("  total song count #max = %d" % max(s["id"] for s in songs))
    print("  takes effect after /reload in game; menu: /trigger menu → double right click")
    return 0


if __name__ == "__main__":
    sys.exit(main())
